apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localcrag-client
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.client.ingress.clusterIssuer | quote }}
spec:
  tls:
    - secretName: {{ .Values.client.ingress.tls.secretName | quote }}
      hosts:
        - {{ .Values.client.ingress.host | quote }}
        - {{ .Values.s3.ingress.s3Host | quote }}
        - {{ .Values.s3.ingress.consoleHost | quote }}
  rules:
    - host: {{ .Values.client.ingress.host | quote }}
      http:
        paths:
          # Send API calls straight to the backend service.
          - path: "/api"
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 5000

          # Everything else goes to the Angular client.
          - path: {{ .Values.client.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: localcrag-client
                port:
                  number: 4200
    - host: {{ .Values.s3.ingress.s3Host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: localcrag-s3
                port:
                  number: 9000
    - host: {{ .Values.s3.ingress.consoleHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: localcrag-s3-console
                port:
                  number: 9001
